### ISSUE TITLE
“复制”按钮表意不明

### ISSUE THREAD

**Issue by wr786** [ASoulCnki/ASoulCnkiFrontEndV3#5]
![image](https://user-images.githubusercontent.com/32223541/144093730-2b109384-cb3c-42bb-881e-81e389990703.png)

如图，正常使用中，上面的“复制”按钮提供的功能是“复制查重结果”；
而下面的“复制”提供的功能是“复制小作文文本”。

在此，上面的“复制”将会产生歧义，且一般更倾向于被理解为“复制当前输入文本框中的文本”。对于第一次使用枝网的用户，甚至可能会不知道哪里可以复制查重结果。

建议是能修改一下文案表述，更加用户友好。

**Comment by ch3cknull** [comment]
fixed in https://github.com/ASoulCnki/ASoulCnkiFrontEndV3/commit/38b3fe99dfd74f73c1638ee287e54ecce2a6f98d

线上已修复 https://asoulcnki.asia
